import { Injectable } from '@angular/core';
import { Activity } from '../models/activity.model';
import { ImpactAnalysisResult } from '../models/ai-result.model';
import { AgentId, AgentFinding, AIResult, Backlog } from '../models/backlog.model';
import { Notification } from '../models/notification.model';
import { Product } from '../models/product.model';
import { User } from '../models/user.model';

export const MOCK_CURRENT_USER: User = {
  id: 'user-po-001',
  name: 'Budi Santoso',
  email: 'budi.santoso@bca.co.id',
  role: 'PO',
  avatar: 'BS',
  productIds: ['prod-001'],
};

export const MOCK_USERS: User[] = [
  MOCK_CURRENT_USER,
  { id: 'user-apo-001', name: 'Sari Dewi', email: 'sari.dewi@bca.co.id', role: 'APO', avatar: 'SD', productIds: ['prod-001'] },
  { id: 'user-ba-001', name: 'Eka Rahayu', email: 'eka.rahayu@bca.co.id', role: 'BA', avatar: 'ER', productIds: ['prod-001'] },
  { id: 'user-dev-001', name: 'Citra Dewi', email: 'citra.dewi@bca.co.id', role: 'Dev', avatar: 'CD', productIds: ['prod-001'], trackIds: ['mobile'] },
  { id: 'user-qa-001', name: 'Fajar Maulana', email: 'fajar.maulana@bca.co.id', role: 'QA', avatar: 'FM', productIds: ['prod-001'] },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name: 'myBCA Mobile',
    description: 'Primary mobile banking app for individual customers',
    category: 'Mobile Banking',
    objective: 'Increase digital engagement and retained customer balance',
    kpi: ['Monthly active users', 'Retained balance', 'Digital transaction frequency'],
    customerSegment: 'Individual BCA customers, age 18-45',
    existingFeatures: ['Transfer', 'QRIS Payment', 'Bill Payment', 'Savings'],
    currentChallenges: ['Competitive feature gap', 'Fragmented budgeting journeys'],
    techStack: ['Angular', 'Node.js', 'PostgreSQL'],
    dependencySystems: ['Core Banking', 'Identity Service', 'Analytics Platform'],
    complianceTags: ['OJK', 'PBI'],
    teamId: 'team-001',
    poId: 'user-po-001',
    apoIds: [],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-002',
    name: 'BCA Mobile Bisnis',
    description: 'Mobile banking for business customers',
    category: 'Business Banking',
    objective: 'Simplify daily financial operations for business customers',
    kpi: ['Active business users', 'Transaction frequency'],
    customerSegment: 'SME business owners',
    existingFeatures: ['Business Transfer', 'Payroll', 'Account Statement'],
    currentChallenges: ['Complex bulk transaction flow'],
    techStack: ['Angular', 'Java', 'Oracle'],
    dependencySystems: ['Core Banking', 'Payroll Engine'],
    complianceTags: ['OJK'],
    teamId: 'team-002',
    poId: 'user-po-001',
    apoIds: [],
    createdAt: new Date('2026-01-01'),
  },
];

const scoredAt = new Date('2026-06-20T10:00:00');

export const MOCK_BACKLOGS: Backlog[] = [
  {
    id: 'qris-retry',
    title: 'Improve QRIS Retry Flow',
    description: 'Retry otomatis dan recovery flow untuk transaksi QRIS yang gagal.',
    businessObjective: 'Meningkatkan transaction success rate.',
    targetUsers: 'Pengguna QRIS aktif.',
    impactArea: ['Revenue', 'CX'],
    supportingEvidence: ['Analytics', 'Complaint Data'],
    estimatedImpact: 'Mengurangi transaksi gagal sebesar 30%.',
    riskIfNotImplemented: 'Lost transaction dan peningkatan komplain.',
    effortEstimation: '10 story points',
    targetQuarter: 'Q2',
    dependency: [],
    completenessScore: 95,
    status: 'ai_scored',
    isEmergency: false,
    aiResult: {
      moscow: 'Must Have',
      reasoning: { summary: 'Prioritas PO sudah tepat.', evidenceRefs: ['QRIS analytics'] },
      confidenceLevel: 85,
      riceScore: { reach: 5, impact: 2, confidence: 85, effort: 10, total: 0.85, reachLabel: 'High Reach' },
      valueEffort: { value: 'High', effort: 'Medium' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'High',
    recommendation: 'keep',
    priorityChangeReason: 'Prioritas PO selaras dengan dampak transaksi dan data komplain.',
    roadmapLane: 'Now',
    createdBy: 'user-po-001',
    createdAt: new Date('2026-04-10'),
    updatedAt: scoredAt,
    productId: 'prod-001',
  },
  {
    id: 'login-biometric',
    title: 'Login Biometrik',
    description: 'Login menggunakan face recognition dan biometric device.',
    businessObjective: 'Mengurangi login friction.',
    targetUsers: 'Pengguna aktif myBCA.',
    impactArea: ['CX', 'Retention'],
    supportingEvidence: ['Survey'],
    estimatedImpact: 'Mengurangi waktu login 60%.',
    riskIfNotImplemented: 'Pengalaman login tertinggal dari kompetitor.',
    effortEstimation: '13 story points',
    targetQuarter: 'Q3',
    dependency: ['identity-v2'],
    completenessScore: 88,
    status: 'ai_scored',
    isEmergency: false,
    aiResult: {
      moscow: 'Should Have',
      reasoning: { summary: 'Tahan sampai dependency siap.', evidenceRefs: ['User survey'] },
      confidenceLevel: 80,
      riceScore: { reach: 10, impact: 2, confidence: 80, effort: 13, total: 1.23, reachLabel: 'Massive Reach' },
      valueEffort: { value: 'High', effort: 'High' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'Medium',
    recommendation: 'defer',
    priorityChangeReason: 'Nilai tinggi, tetapi Identity Service v2 belum siap.',
    roadmapLane: 'Next',
    createdBy: 'user-po-001',
    createdAt: new Date('2026-04-15'),
    updatedAt: scoredAt,
    productId: 'prod-001',
  },
  {
    id: 'dark-mode',
    title: 'Dark Mode',
    description: 'Dukungan dark mode di seluruh layar myBCA.',
    businessObjective: 'Meningkatkan kenyamanan visual.',
    targetUsers: 'Seluruh pengguna myBCA.',
    impactArea: ['CX'],
    supportingEvidence: ['Survey'],
    estimatedImpact: 'Peningkatan kepuasan pengguna.',
    riskIfNotImplemented: 'Dampak bisnis langsung rendah.',
    effortEstimation: '13 story points',
    targetQuarter: 'Q4',
    dependency: [],
    completenessScore: 80,
    status: 'ai_scored',
    isEmergency: false,
    aiResult: {
      moscow: 'Could Have',
      reasoning: { summary: 'Defer setelah backlog berdampak langsung.', evidenceRefs: ['Preference survey'] },
      confidenceLevel: 70,
      riceScore: { reach: 10, impact: 0.5, confidence: 70, effort: 13, total: 0.27, reachLabel: 'Massive Reach' },
      valueEffort: { value: 'Low', effort: 'High' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'Low',
    recommendation: 'defer',
    priorityChangeReason: 'Effort lintas layar tinggi dengan dampak bisnis langsung yang rendah.',
    roadmapLane: 'Later',
    createdBy: 'user-po-001',
    createdAt: new Date('2026-04-20'),
    updatedAt: scoredAt,
    productId: 'prod-001',
  },
  {
    id: 'pocket-rupiah',
    title: 'Pocket Rupiah',
    description: 'Membagi saldo ke beberapa kantong untuk budgeting harian dan tujuan menabung dalam satu aplikasi.',
    businessObjective: 'Meningkatkan engagement dan mempertahankan saldo nasabah di ekosistem myBCA.',
    targetUsers: '80.000 pengguna aktif yang rutin mengatur anggaran dan tujuan tabungan.',
    impactArea: ['Retention', 'CX', 'Revenue'],
    supportingEvidence: ['Analytics', 'Survey'],
    estimatedImpact: '6.400-12.000 adopter potensial dan Rp9,6-30 miliar retained balance.',
    riskIfNotImplemented: 'Nasabah memindahkan aktivitas budgeting dan saldo tujuan ke aplikasi kompetitor.',
    effortEstimation: '8 story points',
    targetQuarter: 'Q4',
    dependency: [],
    completenessScore: 86,
    status: 'new',
    isEmergency: false,
    initialPriority: 'Low',
    recommendation: 'promote',
    priorityChangeReason: '⚠️ ANALISIS KOMPETITOR: Fitur pocket/kantong sudah ada di Jenius sejak 2017 dan blu sejak 2020. BCA tertinggal 6-9 tahun. Urgensi harus dinaikkan dari Q4 ke Q3 untuk mencegah nasabah beralih ke kompetitor yang sudah memiliki fitur matang ini.',
    roadmapLane: 'Later',
    opportunityAtRisk: {
      metric: 'retained_balance',
      min: 9_600_000_000,
      max: 30_000_000_000,
      currency: 'IDR',
      label: 'Rp9,6-30 miliar retained balance',
      formula: '80.000 pengguna × adopsi 8-15% × saldo rata-rata Rp1,5-2,5 juta',
      assumptions: [
        '80.000 pengguna aktif eligible',
        'Adopsi konservatif 8-15%',
        'Saldo rata-rata per pocket Rp1,5-2,5 juta',
      ],
      isDemoEstimate: true,
    },
    evidenceSignals: [
      {
        type: 'competitive',
        label: '⚠️ Feature gap kritis - sudah ada sejak lama',
        detail: 'Jenius meluncurkan Kantong pada 2017 (9 tahun lalu), blu meluncurkan Tabungan Tujuan pada 2020 (6 tahun lalu). BCA sangat tertinggal dalam kapabilitas money management.',
        source: 'Jenius official release 2017, blu official release 2020',
        observedAt: '2017-2020',
      },
      {
        type: 'customer',
        label: 'Customer behavior',
        detail: 'Pengguna membutuhkan pemisahan saldo tanpa berpindah aplikasi. Ekspektasi ini sudah terbentuk sejak 2017.',
        source: 'Market research dan competitor analysis',
        observedAt: '2017-sekarang',
      },
      {
        type: 'delivery',
        label: 'Moderate effort',
        detail: 'Memanfaatkan fondasi rekening dan transfer internal yang telah tersedia.',
        source: 'Asumsi arsitektur demo',
        observedAt: 'Juni 2026',
      },
    ],
    isHistoricalScenario: true,
    source: 'myservice',
    myService: {
      myServiceId: 'MS-2026-0442',
      businessProposalType: 'New Feature',
      featureInitiator: 'Divisi Digital Banking',
      category: 'Savings & Budgeting',
      epic: 'Money Management Experience',
      timeToMarketMonths: 3,
      existingCondition: 'Saldo tabungan belum dapat dipisahkan berdasarkan tujuan atau kategori anggaran.',
      customerValue: 'Nasabah dapat mengatur budgeting dan tujuan menabung tanpa berpindah aplikasi.',
      functionalRequirement: 'Membuat, memberi nama, memindahkan saldo, dan memantau beberapa pocket.',
      concern: 'Perlu definisi perlakuan saldo dan mutasi antar-pocket.',
      userType: 'Nasabah individu aktif',
      valuegraphValue: 'High',
      valuegraphEffort: 'Medium',
      involvementDWH: false,
      involvementRPA: false,
      personalDataAccess: false,
      createdBy: 'Divisi Digital Banking',
      createdOn: new Date('2026-05-12T09:00:00'),
    },
    createdBy: 'user-po-001',
    createdAt: new Date('2026-05-12T09:00:00'),
    updatedAt: scoredAt,
    productId: 'prod-001',
  },
  {
    id: 'recurring-transfer',
    title: 'Recurring Transfer',
    description: 'Jadwal transfer rutin untuk pembayaran tagihan, tabungan, atau kirim uang berkala.',
    businessObjective: 'Meningkatkan retensi dan frekuensi transaksi digital.',
    targetUsers: 'Pengguna aktif myBCA yang melakukan transfer berulang setiap bulan.',
    impactArea: ['Retention', 'Revenue'],
    supportingEvidence: ['Analytics', 'Survey'],
    estimatedImpact: 'Meningkatkan frekuensi transaksi 15%.',
    riskIfNotImplemented: 'Nasabah beralih ke fitur autopay kompetitor.',
    effortEstimation: '7 story points',
    targetQuarter: 'Q2',
    dependency: [],
    completenessScore: 92,
    status: 'ai_scored',
    isEmergency: false,
    aiResult: {
      moscow: 'Must Have',
      reasoning: { summary: 'Fitur ekspektasi pasar yang memengaruhi retensi transaksi.', evidenceRefs: ['Competitor autopay analysis', 'User survey'] },
      confidenceLevel: 82,
      riceScore: { reach: 5, impact: 2, confidence: 82, effort: 7, total: 1.17, reachLabel: 'High Reach' },
      valueEffort: { value: 'High', effort: 'Low' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'High',
    recommendation: 'keep',
    priorityChangeReason: 'Prioritas PO sudah selaras dengan dampak retensi.',
    roadmapLane: 'Now',
    createdBy: 'user-po-001',
    createdAt: new Date('2026-03-15'),
    updatedAt: scoredAt,
    productId: 'prod-001',
  },
  {
    id: 'spending-analytics-v2',
    title: 'Spending Analytics v2',
    description: 'Laporan pengeluaran yang lebih detail dengan kategori otomatis dan insight bulanan.',
    businessObjective: 'Meningkatkan engagement dan literasi keuangan nasabah.',
    targetUsers: 'Seluruh pengguna aktif myBCA.',
    impactArea: ['CX', 'Retention'],
    supportingEvidence: ['Analytics', 'Survey'],
    estimatedImpact: 'Peningkatan engagement 20%.',
    riskIfNotImplemented: 'Pengguna tidak mendapatkan insight keuangan.',
    effortEstimation: '11 story points',
    targetQuarter: 'Q3',
    dependency: [],
    completenessScore: 89,
    status: 'ai_scored',
    isEmergency: false,
    aiResult: {
      moscow: 'Must Have',
      reasoning: { summary: 'Komplemen penting untuk money management experience.', evidenceRefs: ['Usage analytics', 'Customer feedback'] },
      confidenceLevel: 78,
      riceScore: { reach: 10, impact: 2, confidence: 78, effort: 11, total: 1.42, reachLabel: 'Massive Reach' },
      valueEffort: { value: 'High', effort: 'Medium' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'High',
    recommendation: 'keep',
    priorityChangeReason: 'Komplemen strategis untuk pengalaman money management.',
    roadmapLane: 'Next',
    createdBy: 'user-po-001',
    createdAt: new Date('2026-04-01'),
    updatedAt: scoredAt,
    productId: 'prod-001',
  },
  {
    id: 'split-bill',
    title: 'Split Bill',
    description: 'Membagi tagihan grup dan mengirimkan request pembayaran ke teman dalam aplikasi.',
    businessObjective: 'Mendorong peer-to-peer engagement dan transaksi QRIS.',
    targetUsers: 'Pengguna myBCA usia 18-35 yang sering berbagi pengeluaran.',
    impactArea: ['CX', 'Revenue'],
    supportingEvidence: ['Survey'],
    estimatedImpact: 'Adopsi 12.000 pengguna dalam 6 bulan.',
    riskIfNotImplemented: 'Pengguna menggunakan aplikasi e-wallet untuk split bill.',
    effortEstimation: '9 story points',
    targetQuarter: 'Q3',
    dependency: [],
    completenessScore: 84,
    status: 'ai_scored',
    isEmergency: false,
    aiResult: {
      moscow: 'Should Have',
      reasoning: { summary: 'Fitur sosial yang mendukung engagement, tetapi bukan gap kritis.', evidenceRefs: ['Market survey', 'Competitor feature list'] },
      confidenceLevel: 72,
      riceScore: { reach: 5, impact: 1, confidence: 72, effort: 9, total: 0.4, reachLabel: 'High Reach' },
      valueEffort: { value: 'Medium', effort: 'Medium' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'Medium',
    recommendation: 'keep',
    priorityChangeReason: 'Nilai engagement tinggi, tetapi belum menjadi gap utama.',
    roadmapLane: 'Next',
    createdBy: 'user-po-001',
    createdAt: new Date('2026-04-08'),
    updatedAt: scoredAt,
    productId: 'prod-001',
  },
  {
    id: 'virtual-card-control',
    title: 'Virtual Card Control',
    description: 'Kontrol kartu virtual: aktif/nonaktif, batas transaksi, dan notifikasi realtime.',
    businessObjective: 'Meningkatkan keamanan dan kepercayaan nasabah.',
    targetUsers: 'Pengguna kartu virtual myBCA.',
    impactArea: ['Risk', 'CX'],
    supportingEvidence: ['Complaint Data'],
    estimatedImpact: 'Mengurangi klaim fraud 10%.',
    riskIfNotImplemented: 'Risiko fraud meningkat dan komplain bertambah.',
    effortEstimation: '8 story points',
    targetQuarter: 'Q4',
    dependency: [],
    completenessScore: 81,
    status: 'ai_scored',
    isEmergency: false,
    aiResult: {
      moscow: 'Could Have',
      reasoning: { summary: 'Penting untuk risk, tetapi dampak langsung pada growth lebih rendah.', evidenceRefs: ['Complaint trend'] },
      confidenceLevel: 68,
      riceScore: { reach: 5, impact: 1, confidence: 68, effort: 8, total: 0.43, reachLabel: 'High Reach' },
      valueEffort: { value: 'Medium', effort: 'Medium' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'Medium',
    recommendation: 'defer',
    priorityChangeReason: 'Effort moderat dengan dampak growth tidak langsung.',
    roadmapLane: 'Later',
    createdBy: 'user-po-001',
    createdAt: new Date('2026-04-12'),
    updatedAt: scoredAt,
    productId: 'prod-001',
  },
  {
    id: 'loyalty-dashboard',
    title: 'Loyalty Points Dashboard',
    description: 'Dashboard poin loyalitas, riwayat redeem, dan rekomendasi reward.',
    businessObjective: 'Meningkatkan redemptions dan engagement program loyalitas.',
    targetUsers: 'Pengguna program loyalitas myBCA.',
    impactArea: ['CX'],
    supportingEvidence: ['Survey'],
    estimatedImpact: 'Peningkatan redemption rate 8%.',
    riskIfNotImplemented: 'Poin tidak termanfaatkan, engagement program rendah.',
    effortEstimation: '10 story points',
    targetQuarter: 'Q4',
    dependency: [],
    completenessScore: 77,
    status: 'ai_scored',
    isEmergency: false,
    aiResult: {
      moscow: 'Could Have',
      reasoning: { summary: 'Enhancement experience, bukan fitur kritis untuk retensi.', evidenceRefs: ['Loyalty program survey'] },
      confidenceLevel: 65,
      riceScore: { reach: 5, impact: 0.5, confidence: 65, effort: 10, total: 0.16, reachLabel: 'High Reach' },
      valueEffort: { value: 'Low', effort: 'Medium' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'Low',
    recommendation: 'defer',
    priorityChangeReason: 'Dampak langsung rendah dibanding backlog money management.',
    roadmapLane: 'Later',
    createdBy: 'user-po-001',
    createdAt: new Date('2026-04-18'),
    updatedAt: scoredAt,
    productId: 'prod-001',
  },
  {
    id: 'onboarding-redesign',
    title: 'Onboarding Redesign',
    description: 'Redesign alur onboarding myBCA untuk meningkatkan completion rate.',
    businessObjective: 'Meningkatkan activation rate pengguna baru.',
    targetUsers: 'Pengguna baru myBCA.',
    impactArea: ['CX', 'Retention'],
    supportingEvidence: ['Analytics', 'Survey'],
    estimatedImpact: 'Meningkatkan completion rate onboarding 25%.',
    riskIfNotImplemented: 'Drop-off onboarding tinggi terus berlanjut.',
    effortEstimation: '12 story points',
    targetQuarter: 'Q1',
    dependency: [],
    completenessScore: 98,
    status: 'delivered',
    isEmergency: false,
    aiResult: {
      moscow: 'Must Have',
      reasoning: { summary: 'Activation rate adalah funnel utama untuk growth.', evidenceRefs: ['Funnel analytics'] },
      confidenceLevel: 88,
      riceScore: { reach: 5, impact: 3, confidence: 88, effort: 12, total: 1.1, reachLabel: 'High Reach' },
      valueEffort: { value: 'High', effort: 'High' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'High',
    recommendation: 'keep',
    priorityChangeReason: 'Delivery berhasil meningkatkan completion rate onboarding.',
    roadmapLane: 'Now',
    createdBy: 'user-po-001',
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2026-03-30'),
    productId: 'prod-001',
  },
  {
    id: 'statement-download',
    title: 'Statement Download PDF',
    description: 'Unduh e-statement dalam format PDF dengan filter periode.',
    businessObjective: 'Mengurangi kontak call center terkait permintaan statement.',
    targetUsers: 'Seluruh pengguna myBCA.',
    impactArea: ['Ops', 'CX'],
    supportingEvidence: ['Complaint Data'],
    estimatedImpact: 'Mengurangi komplain statement 40%.',
    riskIfNotImplemented: 'Beban call center tetap tinggi.',
    effortEstimation: '6 story points',
    targetQuarter: 'Q1',
    dependency: [],
    completenessScore: 95,
    status: 'delivered',
    isEmergency: false,
    aiResult: {
      moscow: 'Should Have',
      reasoning: { summary: 'Efisiensi operasional yang berdampak langsung pada pengalaman nasabah.', evidenceRefs: ['Complaint data'] },
      confidenceLevel: 80,
      riceScore: { reach: 10, impact: 1, confidence: 80, effort: 6, total: 1.33, reachLabel: 'Massive Reach' },
      valueEffort: { value: 'Medium', effort: 'Low' },
      promptVersion: 'demo-v3.0',
      scoredAt,
    },
    initialPriority: 'Medium',
    recommendation: 'keep',
    priorityChangeReason: 'Berhasil mengurangi beban call center.',
    roadmapLane: 'Next',
    createdBy: 'user-po-001',
    createdAt: new Date('2025-12-15'),
    updatedAt: new Date('2026-02-28'),
    productId: 'prod-001',
  },
];

export const MOCK_POCKET_RUPIAH_AI_RESULT: AIResult = {
  moscow: 'Must Have',
  reasoning: {
    summary: '⚠️ DETEKSI KOMPETITOR: Fitur pocket/kantong telah ada di Jenius (sejak 2017) dan blu (sejak 2020). Urgensi perlu dinaikkan dari Q4 ke Q3 untuk mencegah churn nasabah ke kompetitor yang sudah memiliki fitur ini lebih dulu.',
    evidenceRefs: ['Jenius - Kantong (rilis 2017)', 'blu by BCA Digital - Tabungan Tujuan (rilis 2020)', 'Demo eligible-user assumption'],
  },
  confidenceLevel: 75,
  riceScore: { reach: 5, impact: 3, confidence: 75, effort: 8, total: 1.41, reachLabel: 'High Reach' },
  valueEffort: { value: 'High', effort: 'Medium' },
  promptVersion: 'demo-v3.0',
  scoredAt,
  agentFindings: [
    {
      agentId: 'market-gap',
      agentName: 'Market Gap',
      role: 'Membaca ekspektasi pasar',
      icon: '◎',
      summary: '⚠️ FITUR SUDAH ADA DI KOMPETITOR SEJAK LAMA: Jenius meluncurkan "Kantong" pada 2017 (9 tahun lalu), blu meluncurkan "Tabungan Tujuan" pada 2020 (6 tahun lalu). BCA tertinggal signifikan dalam kapabilitas money management.',
      contributesTo: ['Impact', 'Confidence'],
      evidence: ['Jenius Kantong - launched 2017', 'blu Tabungan Tujuan - launched 2020', 'Public competitor references'],
    },
    {
      agentId: 'business-impact',
      agentName: 'Customer & Business Impact',
      role: 'Mengestimasi opportunity at risk',
      icon: '↗',
      summary: 'Dengan asumsi konservatif, 6.400-12.000 pengguna dapat mempertahankan Rp9,6-30 miliar saldo. Risiko churn meningkat karena kompetitor sudah memiliki fitur ini bertahun-tahun.',
      contributesTo: ['Reach', 'Impact'],
      evidence: ['Demo adoption and balance assumptions', 'Competitor feature maturity analysis'],
    },
    {
      agentId: 'feasibility-risk',
      agentName: 'Feasibility & Risk',
      role: 'Menilai effort dan trade-off',
      icon: '◇',
      summary: 'Effort moderat dan tidak memiliki blocker kritis; risiko terbesar adalah terlambat mengejar ekspektasi pasar yang sudah terbentuk sejak 2017.',
      contributesTo: ['Effort', 'MoSCoW'],
      evidence: ['Existing transfer and account capabilities', 'Market expectation established since 2017'],
    },
  ],
};

export interface AgentDefinition {
  id: AgentId;
  name: string;
  role: string;
  icon: string;
  steps: string[];
}

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  { id: 'market-gap', name: 'Market Gap', role: 'Mendeteksi tren kompetitor & opportunity loss', icon: '◎', steps: ['Menganalisis tren kompetitor...', 'Mengevaluasi urgensi pasar...', 'Menentukan target rilis optimal...'] },
  { id: 'business-impact', name: 'Customer & Business Impact', role: 'Memvalidasi keselarasan dengan OKR Produk', icon: '↗', steps: ['Menyelaraskan dengan KPI Produk...', 'Mengkuantifikasi Reach & Impact...'] },
  { id: 'feasibility-risk', name: 'Feasibility & Risk', role: 'Memindai blocker & regulasi', icon: '◇', steps: ['Menganalisis kompleksitas code...', 'Memindai regulasi BI/OJK...', 'Memeriksa proteksi data...'] },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act-qris-001', type: 'ai_scored', actor: 'AIPRO AI', actorRole: 'PO',
    description: 'AI scoring completed: Improve QRIS Retry Flow',
    subDescription: 'confidence 85% · Must Have',
    backlogId: 'qris-retry', backlogTitle: 'Improve QRIS Retry Flow', timestamp: new Date('2026-06-18T09:00:00'), productId: 'prod-001',
  },
  {
    id: 'act-login-001', type: 'ai_scored', actor: 'AIPRO AI', actorRole: 'PO',
    description: 'AI scoring completed: Login Biometrik',
    subDescription: 'confidence 80% · Should Have',
    backlogId: 'login-biometric', backlogTitle: 'Login Biometrik', timestamp: new Date('2026-06-19T10:00:00'), productId: 'prod-001',
  },
  {
    id: 'act-darkmode-001', type: 'ai_scored', actor: 'AIPRO AI', actorRole: 'PO',
    description: 'AI scoring completed: Dark Mode',
    subDescription: 'confidence 70% · Could Have',
    backlogId: 'dark-mode', backlogTitle: 'Dark Mode', timestamp: new Date('2026-06-19T14:00:00'), productId: 'prod-001',
  },
  {
    id: 'act-pocket-001', type: 'ai_scored', actor: 'AIPRO AI', actorRole: 'PO',
    description: '⚠️ Priority mismatch detected: Pocket Rupiah',
    subDescription: 'PO Low → AI Must Have · confidence 75%',
    backlogId: 'pocket-rupiah', backlogTitle: 'Pocket Rupiah', timestamp: new Date('2026-06-20T10:00:00'), productId: 'prod-001',
  },
  {
    id: 'act-pocket-002', type: 'warning', actor: 'AIPRO AI', actorRole: 'PO',
    description: '⚠️ DETEKSI KOMPETITOR: Fitur pocket sudah ada di Jenius (2017) dan blu (2020)',
    subDescription: 'BCA tertinggal 6-9 tahun · Urgensi perlu dinaikkan dari Q4 ke Q3',
    backlogId: 'pocket-rupiah', backlogTitle: 'Pocket Rupiah', timestamp: new Date('2026-06-20T10:05:00'), productId: 'prod-001',
  },
  {
    id: 'act-pocket-003', type: 'human_override', actor: 'Budi Santoso', actorRole: 'PO',
    description: 'Reviewed AIPRO recommendation for Pocket Rupiah',
    subDescription: 'Human decision required before roadmap change',
    backlogId: 'pocket-rupiah', backlogTitle: 'Pocket Rupiah', timestamp: new Date('2026-06-20T10:10:00'), productId: 'prod-001',
  },
  {
    id: 'act-onboarding-001', type: 'backlog_delivered', actor: 'Citra Dewi', actorRole: 'Dev',
    description: 'Onboarding Redesign delivered',
    subDescription: 'Completion rate onboarding naik 25%',
    backlogId: 'onboarding-redesign', backlogTitle: 'Onboarding Redesign', timestamp: new Date('2026-03-30T09:00:00'), productId: 'prod-001',
  },
  {
    id: 'act-statement-001', type: 'backlog_delivered', actor: 'Fajar Maulana', actorRole: 'QA',
    description: 'Statement Download PDF delivered',
    subDescription: 'Komplain statement turun 40%',
    backlogId: 'statement-download', backlogTitle: 'Statement Download PDF', timestamp: new Date('2026-02-28T09:00:00'), productId: 'prod-001',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-qris', type: 'ai_scored', title: 'AI scoring completed',
    body: 'Improve QRIS Retry Flow telah di-score (confidence 85%).',
    isRead: true, actionUrl: '/backlog/qris-retry', timestamp: new Date('2026-06-18T09:00:00'),
  },
  {
    id: 'notif-login', type: 'ai_scored', title: 'AI scoring completed',
    body: 'Login Biometrik telah di-score (confidence 80%).',
    isRead: true, actionUrl: '/backlog/login-biometric', timestamp: new Date('2026-06-19T10:00:00'),
  },
  {
    id: 'notif-darkmode', type: 'ai_scored', title: 'AI scoring completed',
    body: 'Dark Mode telah di-score (confidence 70%).',
    isRead: true, actionUrl: '/backlog/dark-mode', timestamp: new Date('2026-06-19T14:00:00'),
  },
  {
    id: 'notif-pocket', type: 'ai_scored', title: '⚠️ Priority mismatch detected',
    body: 'Pocket Rupiah dinilai Must Have meskipun prioritas awal PO masih Low.',
    isRead: false, actionUrl: '/backlog/pocket-rupiah', timestamp: new Date('2026-06-20T10:00:00'),
  },
  {
    id: 'notif-pocket-competitor', type: 'myservice_new', title: '⚠️ DETEKSI KOMPETITOR - Fitur sudah ada sejak lama',
    body: 'Fitur pocket/kantong sudah ada di Jenius (2017) dan blu (2020). BCA tertinggal 6-9 tahun. Urgensi perlu dinaikkan dari Q4 ke Q3.',
    isRead: false, actionUrl: '/backlog/pocket-rupiah', timestamp: new Date('2026-06-20T10:05:00'),
  },
];

export const MOCK_IMPACT_RESULTS: Record<string, ImpactAnalysisResult> = {
  'pocket-rupiah': {
    backlogId: 'pocket-rupiah',
    targetLane: 'Q3',
    roadmapImpacts: [
      { affectedBacklogId: 'split-bill', affectedBacklogTitle: 'Split Bill', description: 'Bergeser ke Q4 karena Q3 capacity terbatas dan Pocket Rupiah memiliki urgensi kompetitor lebih tinggi.', severity: 'medium' },
      { affectedBacklogId: 'virtual-card-control', affectedBacklogTitle: 'Virtual Card Control', description: 'Tetap di Later; tidak ada perubahan prioritas.', severity: 'low' },
    ],
    dependencyImpacts: [],
    kpiImpacts: [
      { kpi: 'Retained balance', description: 'Membuka opportunity Rp9,6-30 miliar berdasarkan skenario demo.', severity: 'high' },
      { kpi: 'Engagement', description: 'Menambah alasan pengguna mengelola uang tanpa berpindah aplikasi.', severity: 'medium' },
      { kpi: 'Competitive gap', description: '⚠️ BCA tertinggal 6-9 tahun dari kompetitor (Jenius 2017, blu 2020). Perlu segera dikejar.', severity: 'high' },
    ],
    estimatedDelayInSprints: 0,
    aiRecommendation: '⚠️ PROMOSIKAN SEGERA: Pocket Rupiah harus dipromosikan dari Q4 ke Q3. Trade-off utamanya adalah menunda Split Bill ke Q4, tetapi spending analytics v2 tetap di Q3 karena komplemen strategis. Tidak ada blocker kritis.',
    recommendedAction: 'promote',
  },
  'qris-retry': {
    backlogId: 'qris-retry', targetLane: 'Q2', roadmapImpacts: [], dependencyImpacts: [],
    kpiImpacts: [{ kpi: 'Transaction success rate', description: 'Tetap menjadi komitmen aktif.', severity: 'high' }],
    estimatedDelayInSprints: 0, aiRecommendation: 'Pertahankan di Now.', recommendedAction: 'keep',
  },
  'login-biometric': {
    backlogId: 'login-biometric', targetLane: 'Q4', roadmapImpacts: [],
    dependencyImpacts: [{ dependencyId: 'identity-v2', dependencyTitle: 'Identity Service v2', description: 'Belum siap untuk delivery.', isBlocker: true }],
    kpiImpacts: [], estimatedDelayInSprints: 2, aiRecommendation: 'Tunda hingga Identity Service v2 siap.', recommendedAction: 'defer',
  },
  'dark-mode': {
    backlogId: 'dark-mode', targetLane: 'Q4', roadmapImpacts: [], dependencyImpacts: [], kpiImpacts: [],
    estimatedDelayInSprints: 0, aiRecommendation: 'Letakkan di Later setelah backlog berdampak langsung.', recommendedAction: 'defer',
  },
};

export const MOCK_IMPACT_RESULT = MOCK_IMPACT_RESULTS['pocket-rupiah'];

@Injectable({ providedIn: 'root' })
export class MockDataService {
  getBacklogs(): Backlog[] { return [...MOCK_BACKLOGS]; }
  getUsers(): User[] { return [...MOCK_USERS]; }
  getProducts(): Product[] { return [...MOCK_PRODUCTS]; }
  getActivities(): Activity[] { return [...MOCK_ACTIVITIES]; }
  getNotifications(): Notification[] { return [...MOCK_NOTIFICATIONS]; }
  getCurrentUser(): User { return { ...MOCK_CURRENT_USER }; }
  getImpactResult(): ImpactAnalysisResult { return { ...MOCK_IMPACT_RESULT }; }
}
